# Generated by Django 3.2.15 on 2022-09-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_talk', '0006_alter_anonymoustalk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoustalk',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
