# Generated by Django 3.2.15 on 2022-09-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_talk', '0007_alter_anonymoustalk_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='anonymoustalk',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='anonymous_talk.reply'),
        ),
    ]
