# Generated by Django 3.1.7 on 2021-12-02 17:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
        migrations.RenameModel(
            old_name='Talks',
            new_name='Talk',
        ),
        migrations.RenameModel(
            old_name='teachers',
            new_name='teacher',
        ),
    ]
