# Generated by Django 3.1.7 on 2021-12-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211202_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.CharField(default='بدون توضیحات', max_length=128),
        ),
    ]
