# Generated by Django 3.1.7 on 2021-12-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='بدون توضیحات', max_length=64),
        ),
        migrations.AlterField(
            model_name='report',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reports/video'),
        ),
        migrations.AlterField(
            model_name='report',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='reports/voice/'),
        ),
    ]
