# Generated by Django 3.1.7 on 2021-12-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211203_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='reports/voice'),
        ),
    ]
