# Generated by Django 3.1 on 2022-08-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211203_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
