# Generated by Django 3.1 on 2022-08-05 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_talk_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.talk'),
        ),
    ]
