# Generated by Django 3.1 on 2022-08-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_talk_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'verbose_name': 'دلنوشته', 'verbose_name_plural': 'دلنوشته ها'},
        ),
    ]
