# Generated by Django 3.1 on 2022-08-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220805_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('logo_small', models.FileField(upload_to='homepage')),
                ('logo_medium', models.FileField(upload_to='homepage')),
                ('logo_large', models.FileField(upload_to='homepage')),
                ('desription', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'گزارش', 'verbose_name_plural': 'گزارش ها'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'جلسه', 'verbose_name_plural': 'جلسات'},
        ),
    ]
