# Generated by Django 3.1 on 2022-08-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220807_2018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Status',
        ),
    ]
