# Generated by Django 4.1 on 2022-08-07 16:25

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_date_talk_date_m_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
