# Generated by Django 4.1 on 2022-08-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_talk_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='date_m',
        ),
    ]
