# Generated by Django 3.2.15 on 2022-09-02 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_talk_date_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='videos')),
            ],
        ),
        migrations.AlterField(
            model_name='talk',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 9, 2, 10, 53, 18, 764056, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
