# Generated by Django 3.2.15 on 2022-09-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220902_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinformation',
            name='logo_large',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='logo_medium',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='logo_small',
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='eitaa',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='instagram',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='telegram',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
