# Generated by Django 3.2.15 on 2022-10-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20220927_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinformation',
            old_name='desription',
            new_name='description',
        ),
    ]
